### ISSUE TITLE
Improvement of documents (phase 1)

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/Colors.jl#398]
The current documentation is categorized by technical field, so it is difficult for beginners to understand. For example, beginners will first read the [Colorspaces](http://juliagraphics.github.io/Colors.jl/v0.11/colorspaces/) page. However the page contains documents which most beginners do not need, such as CMFs.

Of course, adding a tutorial page is a good idea. However, I think there is still room for improvement.

The following is my plan.

## Introduction
- [x] Simplify the supported colorspaces (PR #406)
  - They are also in the "Colorspaces" page.
- [x] Add the installation instructions, i.e. `]add Colors` (PR #406)
- [x] Add notes for "reexport" (PR #406)

### Available colorspaces
- [x] Add inline figures showing the examples of 2-D cross sections (PR #406)
### :new: Constructors
- [ ] Add examples of constructors (e.g. `RGB`, `RGB{Float64}`, `RGBA`, `ARGB32`)
  - The constructors are implemented in ColorTypes.jl, so only examples are given there.
- [ ] Add notes for `Normed`
### :new: Generating random colors
- [ ] Add notes for non-RGB colors
- [ ] Add examples for sampling `RGB24` colors without replacement
  - cf. issue #434
### Color parsing
- [x] Add the explicit reference to `hex` (PR #406)
- [x] Add the link to "Named Colors" (PR #406)
### Color conversion
- [ ] Add examples with the extra arguments (e.g. `alpha`, `wp`)
## :new: Displaying colors
- [ ] Add the document about color swatches

## Color Differences (<-- Colorspaces)
- [x] Use docstrings (PR #409)
- [x] Add some graphical examples (PR #409)

### Color interpolation (<-- Generating a range of colors, Weighted color means)
- [ ] Add notes for the vector space and the reference to ColorVectorSpace.jl
- [x] Add examples for non-RGB color types. (PR #405)

#### Sequential and diverging color palettes
- [ ] Move the details to the docstrings of `sequential_palette()`/`diverging_palette`
- [ ] Add inline example figures

### Generating distinguishable colors
- [ ] Move the details to the docstring of `distinguishable_colors()`
- [ ] Add inline example swatches
- [ ] Add figures to explain the `seed`
- [x] Update the `PyPlot` example with `dropseed` (PR #415)
  - It looks like the sample numbers are different between the actual plot and the script.

## Named Colors
- [x] Move the instructions and code examples to "Construction and Conversion" (PR #406)

### Chromatic adaptation (white balance)
- [ ] Add the note for problem with whitepoint handling
- [ ] Add notes about CAMs and CATs
### Simulation of color deficiency ("color blindness")
- [x] Add inline figures showing the examples (PR #413)
### Most saturated color (<-- Colorscales)
- [x] Move the MSC document from "Colorscales" to "Advanced Functions" (PR #404)

### Migrating from Color.jl (--> null)
- [x] Eliminate the Color.jl migration page (PR #404)

**Comment by timholy** [comment]
This would be *fantastic*

**Comment by cormullion** [comment]
Good stuff.

You might be able to get a few useful snippets from one of my earlier attempts at improving the documentation [here](https://github.com/JuliaAttic/Color.jl/pull/98/files#diff-04c6e90faac2675aa89e2176d2eec7d8). 😂  The current docs were more of a basic “move it to Documenter format”.

**Comment by kimikage** [comment]
> You intend to do this after version 1 is released, I suppose?

Some of the above are linked to source code changes, so I think we should start right away. In order to keep the commit log clean and to make the review easier, it is better to merge some units of changes to the master branch. However, I don't think that the timing needs to be synchronized with the releases.

One thing to watch out for is content movement, i.e. problems with dead links.

**Comment by kimikage** [comment]
> Add inline figures showing the examples of 2-D cross sections

SVG + CSS (w/o script) :stuck_out_tongue_closed_eyes:
https://jsfiddle.net/ycmd890n/5/

By using PNGs (in base64) for the bitmaps instead of the `<path>`s, I think it will be a little lighter.

**Comment by kimikage** [comment]
16x16 PNGs version (ImageMagick-free)
![colorspaces](https://user-images.githubusercontent.com/12679384/74844496-def0ff80-5370-11ea-8b08-50ed363d86ce.png)

**Comment by cormullion** [comment]
They’re very pretty! But how big are they going to be, and can I use them on my iPad tablet?

**Comment by kimikage** [comment]
cf. https://github.com/kimikage/Colors.jl/tree/docs_crosssection

> But how big are they going to be, and can I use them on my iPad tablet?

Does the "big" mean their display sizes? It should be about 1 inch per chart. Since there are nine charts now, they may be annoying on smartphones. In terms of data size, it is about 20KB per chart.

I do not have an iPad, but on my smartphone it worked. However, mouse hovering is not available on touch devices. Also, dragging is not supported. You need to touch the color bar.

**Comment by cormullion** [comment]
I'm thinking about accessibility... I think they should be larger. ¯\\_(ツ)_/¯

**Comment by kimikage** [comment]
Scaling is easy because they are just SVG images. 
I accept feedbacks on accessibility. However, keep in mind that this is not a color tool but a manual. :smile:
I am writing this as doctests. TBH, I first learned that Luv produces false colors in the low L region due to out-of-gamut problems.

**Comment by cormullion** [comment]
I didn’t change anything- my phone is playing up with rain on the screen. 💦💦💦

**Comment by timholy** [comment]
For the color panes, what about always plotting something closest to intensity in the "colorbar" to the right? I'm noting the difference in immediate subjective impression that Lab and Luv have vs. LCHab and LCHuv. If you switched the latter two to the format of the first two (putting L* in the colorbar and using the x/y plot for a/b and u/v respectively), I suspect it would make it easier to understand the similarities/differences.

**Comment by cormullion** [comment]
![On my phone](https://user-images.githubusercontent.com/52289/74923288-6b7adc80-53c8-11ea-99c5-e909b17fb6db.png)

**Comment by kimikage** [comment]
Thank you for the report, @cormullion. I checked it on Chrome, Firefox, IE11 and (old) Edge but not on Safari, because I do not have the devices on which Safari runs.(I have MBP Mid 2009, though.)

TBH, I noticed that it didn't work on IE11 and Edge, but I didn't care about that because that is the usual characteristic of IE and Edge. :sweat_smile:

Interestingly, the screenshot is similar to the IE11's result. Probably a trivial problem with the `<image>` elements.

**Comment by cormullion** [comment]
It might be OK for the docs to not work perfectly on all platforms, I suppose.... if there was a message about it not working it would be less confusing... And docs should never be confusing.😀

**Comment by johnnychen94** [comment]
FYI, safari 13.0.5 on my MBP (macOS Catalina) looks the same as on that of @cormullion

**Comment by kimikage** [comment]
IE11 and Edge are supported now.
![ie11](https://user-images.githubusercontent.com/12679384/74960820-59448100-5450-11ea-9d4c-a0a650f86235.png)

I added the extra HSV, HSL and HSI. (I did not add the LCHab and LCHuv charts. The implementation of `crosssection()` is a bit tricky, but it is simple to use, so you can easily try it in a local environment.)

Personally, I prefer my original version (i.e. ”H" is the z axis).

**Comment by johnnychen94** [comment]
safari works as well (and you're such a perfectionist!)

**Comment by timholy** [comment]
> Personally, I prefer my original version (i.e. ”H" is the z axis).

To clarify, what I was pointing out that the version in https://github.com/JuliaGraphics/Colors.jl/issues/398#issuecomment-588270497 might make someone say, "wow, LCHab and LCHuv are really different from Lab and Luv! Why did they give them such similar names?" I'm not particularly choosy about which axis gets assigned to the color bar vs the 2d slice, just suggesting that we make them consistent where possible.

But in the end, if you're doing the work, I think you should choose.

**Comment by kimikage** [comment]
I implicitly assume that the person who compare the characteristics of color spaces understands the relationship between Lab and LCHab. That allows the person to compare HSV with LCHab instead of Lab.

In fact, this inconsistency is due to the particularity of the cylindrical (cyclic) color spaces. In that respect LCHab and LCHuv are really different from Lab and Luv. 
These are for color "type" comparisons rather than color spaces.

I'm not particularly choosy about which axis gets assigned to the color bar, too. I'll add the extra LCHab and LCHuv charts with L* color bar temporarily.

**Comment by kimikage** [comment]
I added some examples for [`range`](http://juliagraphics.github.io/Colors.jl/latest/colormapsandcolorscales/#Generating-a-range-of-colors-1).
This is really off-topic, but I like the dynamic figure generation when building documentation. Why don't JuliaImages use the dynamic generation? (https://juliaimages.org/latest/conversions_views/#Using-colorview-to-make-color-overlays-1) :smile:

**Comment by timholy** [comment]
We probably should. I'm not sure Documenter initially offered such good support for behind-the-scenes code evaluation as it does now.

**Comment by cormullion** [comment]
Most of Luxor's docs' graphics are generated when the docs are built. Never done it for anything else, though.

**Comment by kimikage** [comment]
I've planned to clean up `differences.jl`, but one of the problems is the lack of tests.
The following charts are not suggestive, but I think it might be slightly helpful for the regression test.
![colordiff](https://user-images.githubusercontent.com/12679384/75323280-e60b9680-58b7-11ea-9767-b78f26d4c82d.png)

**Comment by kimikage** [comment]
FYI, `DE_CMC` is not metric but quasimetric. So, we cannot draw the triangle with `DE_CMC`.
```
64.6 + 38.9 < 105
```
I think it's kind if we have any additional notes.

**Comment by cormullion** [comment]
These are very cool! They could - dare I say again - do with being a little larger - they're quite cramped to  my eyes.

**Comment by kimikage** [comment]
The cross-sectional chart (PR #406) should not be too large due to the page layout. On the other hand, there are less limitations on the sizes of the charts for `colordiff`. I tried to make them larger.
Of cource, they are compatible with the dark theme.
![colordiff2](https://user-images.githubusercontent.com/12679384/75336628-d21f5f00-58ce-11ea-8e39-7170ffd3ce6b.png)

**Comment by cormullion** [comment]
Do the differing sizes of the circles mean anything? Perhaps they don't need to scale...

**Comment by kimikage** [comment]
This is a tautology, but the difference in size represents the differences of scale. Paradoxically, the  circle sizes are different because I did not scale the circles.

**Comment by cormullion** [comment]
I think the different radii confused me, because I thought them significant - but they’re really symbolic so should be the same.  My 2 cents. 😀

**Comment by kimikage** [comment]
The difference in scale means the difference in the return value of `colordiff`, so the "visual" difference is important as the "tests". It is easy to unify the apparent size of the circles, but we lose one dimension of visual information.

The problem is that we feel the "largeness" of a circle mainly by its area rather than its radius, so the differences are over-emphasized. However, it is convenient for testing, even though it confuses general users.:sweat_smile:

**Comment by cormullion** [comment]
Perhaps an explanatory note would be sufficient then.

**Comment by kimikage** [comment]
> The difference in the size of circles in the charts above represents the difference in the scale. The radii of the circles are all 20 in their scale units, so  larger circles mean that the metric returns smaller values. Therefore, we should not compare the color differences between different metrics.

too tedious?

**Comment by cormullion** [comment]
It's beginner friendly though! :)

**Comment by kimikage** [comment]
I will add the captions.
![dificiency](https://user-images.githubusercontent.com/12679384/76148040-c1989100-60e5-11ea-8563-f4162fccd46a.png)

I wanted an image which fits:
- no problem with copyright
- colorful
- including green, red and brown

However, there is no such image in TestImages.jl.:sweat_smile:

**Comment by timholy** [comment]
Oh dear, are there images in TestImages where we should be concerned about copyright? I thought we had been pretty careful about that.

**Comment by kimikage** [comment]
I'm sorry if I may have been unclear.
I don't think that the images in TestImages.jl have "practically" copyright problems. (However, strictly speaking, some images (e.g. "Peppers") do not have the clear source or copyright status. cf. http://sipi.usc.edu/database/copyright.php)

I think the images in TestImages.jl are not suitable for the simulating color deficiency in terms of color. Scanned images of printed materials (e.g. "Peppers", including green and red) do not have "natural" colors.

In fact, I'm not satisfied with the results of "Peppers".
```julia
protanopic.(testimage("peppers"), 0.8)
```
![peppers](https://user-images.githubusercontent.com/12679384/76155703-0d255c00-6133-11ea-912d-3f1a756eed01.png)
BTW, I am concerned that red is too dark than other tools, although I don't know the "correct" result.

**Comment by kimikage** [comment]
BTW, Julia v1.0 is no longer used for the document generation, so we can use PNGFiles.jl.

**Comment by timholy** [comment]
Just a general note, it's unclear to me and perhaps others whether you're waiting on something from reviewers. The PR title says "RFC" but there has indeed been a great deal of comment, almost all of which is favorable and none of which seems like a deal-breaker.

I know you have a lot of unchecked boxes above, so maybe you're just waiting until you finish everything. But a PR doesn't have to solve all problems if it solves some. Feel free to just merge pieces of this and post the rest as an issue.

**Comment by kimikage** [comment]
I'm going to close this once and for all since I can no longer spend as much time on this as I did when I first opened it.

There were valuable discussions, and I certainly think the documentation has improved. :tada:

However, I also think this has a little too much context to continue. I'd like to make it a little easier for everyone to update the documentation.

Thanks!

**Comment by timholy** [comment]
Oh, shoot, I thought this was a PR. But sure, fine to close it. And indeed they have improved!
